server:
  port: 8080
  servlet:
    context-path: /go-activity
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/go_activity?serverTimezone=Asia/Shanghai
    username: root
    password: xujinjing
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      shutdown-timeout: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0

mybatis:
  type-aliases-package: com.jackie.goactivitymybatis.entity
  configuration:
    map-underscore-to-camel-case: true